user_token: YTkyMmNiNTktN2ZjNS00ZTRmLWI2MTMtOGRhOGNiMTU4ODVkXzE0NjU=

session:
  key: key_to_generate
admin:
  email: admin@admin.com
  password: admin
bot:
  token: vk1.a.mEQL5quVNfO69imvNYxx-vMtniC6gA7kPB-gMT9HjDkqj03NqoiV7iFnucBoE6ot8457ikDONoLdHiryVJ-GVlIPAPA_MMlibVkZ16xyFNNErhp3j3BRlncKusHozhUG9xZuM-io_s6peyGXk-ZvWAYsb7cNwYzovzLERumRq5stjZV7hPJvONe0mNKwBDVfTjHN63VFyKSGtGEQBW5FNg
  group_id: 222332768
