user_token: YTkyMmNiNTktN2ZjNS00ZTRmLWI2MTMtOGRhOGNiMTU4ODVkXzgwNg==

session:
  key: key_to_generate
admin:
  email: admin@admin.com
  password: admin
bot:
  token: 1e97e9e38648ddcc89eaa01f1b41c6f37f39fc4879805eec5b0d83055dd8244bd13c3174770a8d1d4f2ce
  group_id: 210523391
